-- USER SQL
CREATE USER "chef" IDENTIFIED BY "Password123"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";



-- QUOTAS



-- ROLES



-- SYSTEM PRIVILEGES
GRANT SELECT ANY TABLE TO "chef" ;
GRANT DELETE ANY TABLE TO "chef" ;
GRANT UPDATE ANY TABLE TO "chef" ;
GRANT INSERT ANY TABLE TO "chef" ;






CREATE TABLE "chef".LOGIN (
    ID NUMBER NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    FIRSTNAME VARCHAR2(100) NOT NULL,
    LASTNAME VARCHAR2(100) NOT NULL);
    
alter table "chef".LOGIN add(
    CONSTRAINT login_pk PRIMARY KEY (ID));
    
CREATE SEQUENCE login_seq START WITH 1;






CREATE TABLE "chef".recipe (
    ID NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    STYLE VARCHAR2(100) NOT NULL,
    INGREDIENT1 VARCHAR2(100) NOT NULL,
    INGREDIENT2 VARCHAR2(100) NOT NULL,
    INGREDIENT3 VARCHAR2(100) NOT NULL,
    INGREDIENT4 VARCHAR2(100) NOT NULL,
    INGREDIENT5 VARCHAR2(100) NOT NULL,
    RECIPE VARCHAR2(4000) NOT NULL);
    
alter table "chef".recipe add(
    CONSTRAINT recipe_pk PRIMARY KEY (ID));
    
CREATE SEQUENCE recipe_seq START WITH 1;-- USER SQL
CREATE USER "chef" IDENTIFIED BY "Password123"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";



-- QUOTAS



-- ROLES



-- SYSTEM PRIVILEGES
GRANT SELECT ANY TABLE TO "chef" ;
GRANT DELETE ANY TABLE TO "chef" ;
GRANT UPDATE ANY TABLE TO "chef" ;
GRANT INSERT ANY TABLE TO "chef" ;






CREATE TABLE "chef".LOGIN (
    ID NUMBER NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    FIRSTNAME VARCHAR2(100) NOT NULL,
    LASTNAME VARCHAR2(100) NOT NULL);
    
alter table "chef".LOGIN add(
    CONSTRAINT login_pk PRIMARY KEY (ID));
    
CREATE SEQUENCE login_seq START WITH 1;






CREATE TABLE "chef".recipe (
    ID NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    STYLE VARCHAR2(100) NOT NULL,
    INGREDIENT1 VARCHAR2(100) NOT NULL,
    INGREDIENT2 VARCHAR2(100) NOT NULL,
    INGREDIENT3 VARCHAR2(100) NOT NULL,
    INGREDIENT4 VARCHAR2(100) NOT NULL,
    INGREDIENT5 VARCHAR2(100) NOT NULL,
    RECIPE VARCHAR2(4000) NOT NULL);
    
alter table "chef".recipe add(
    CONSTRAINT recipe_pk PRIMARY KEY (ID));
    
CREATE SEQUENCE recipe_seq START WITH 1;